services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_ai_app
    restart: unless-stopped
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TZ=Europe/Zurich
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_ai_bot
    network_mode: host
    restart: unless-stopped
    command: python -m app.bot.bot
    env_file:
      - .env
    environment:
      - TZ=Europe/Zurich
      - POSTGRES_HOST=127.0.0.1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /home/petroprog/.ssh:/home/appuser/.ssh:ro

  postgres:
    image: postgres:16-alpine
    container_name: news_ai_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Europe/Zurich
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: news_ai_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2500M

volumes:
  postgres_data:
    driver: local
  ollama_data:
    driver: local