import json
import logging
from typing import Any, Dict, List, Optional
import httpx
from pydantic import BaseModel, Field

from app.config import get_settings

logger = logging.getLogger("news_ai.ai.client")
settings = get_settings()


class ArticleAnalysisResult(BaseModel):
    """Structured analytical output generated by the local LLM."""

    russian_title: Optional[str] = Field(None, description="Заголовок новости на русском языке")
    short_summary: str = Field(..., description="1-2 sentences summary in Russian")
    why_it_matters: str = Field(..., description="Why it matters in Russian")
    key_points: List[str] = Field(default_factory=list, description="2-3 key points in Russian")
    importance_score: float = Field(..., ge=1.0, le=10.0, description="Importance score")
    category: str = Field("IT", description="Topic category")


class OllamaClient:
    """Asynchronous client optimized for AI analysis with local LLM."""

    def __init__(
        self,
        base_url: Optional[str] = None,
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> None:
        self.base_url = (base_url or settings.OLLAMA_BASE_URL).rstrip("/")
        self.model = model or settings.OLLAMA_MODEL
        self.timeout = timeout or 180.0

    async def analyze_article(
        self,
        title: str,
        text: str,
        source_name: Optional[str] = None,
    ) -> Optional[ArticleAnalysisResult]:
        """Analyze article and return structured JSON."""
        system_prompt = (
            "Ты — ведущий AI-аналитик новостей технологий, киберспорта и оперативных событий.\n"
            "Проанализируй текст новости и верни СТРОГО валидный JSON без markdown:\n\n"
            "Правила классификации:\n"
            "1. Доступные категории: 'IT', 'AI & Нейросети', 'Linux & Инфраструктура', 'CS2', 'Украина'.\n"
            "2. В категорию 'Украина' относи ВСЕ новости о ситуации в Украине, атаках, обстрелах, ПВО, городах (Дніпро / Днепр, Киев, Одесса, Харьков), международной политике (ООН, НАТО), ТЦК и энергетике. Все посты из канала NovynaUKR СТРОГО относи к категории 'Украина'!\n"
            "3. В категорию 'CS2' относи ВСЕ новости о CS2, CS:GO, киберспорте, турнирах (StarLadder, Major, BLAST, ESL), матчах, командах (NaVi, Vitality, Spirit, FaZe, FUT, MOUZ, Falcons, G2), игроках (s1mple, m0NESY, ZywOo, donk) и мобильных играх (Clash Royale). Игры и киберспорт СТРОГО ЗАПРЕЩЕНО относить к 'IT'!\n"
            "4. В категорию 'IT' относи новости об IT, программировании, языках программирования (Python, Rust, Go, C++, TypeScript/JS, Java, C#, Zig, Mojo), их компиляторах, архитектуре и технологиях.\n"
            "5. В категорию 'AI & Нейросети' относи новости об LLM, нейросетях, моделях и ИИ-инструментах.\n"
            "6. В категорию 'Linux & Инфраструктура' относи релизы ядра Linux, дистрибутивов, DevOps, Kubernetes, серверного ПО.\n\n"
            "Правила оценки важности (importance_score от 1.0 до 10.0):\n"
            "- Для категории 'Украина':\n"
            "  * 3.0 - 5.0 (Низкая важность / оперативные микро-сигналы): короткие предупреждения о пролете единичных дронов/шахедов ('шахед курсом на...', 'угроза по баллистике', 'тревога в области', 'летит дрон'). Это микро-сообщения, не ставь им высокую оценку!\n"
            "  * 7.5 - 9.5 (Высокая важность): итоговые утренние сводки атак Воздушных сил (сколько сбито за ночь), важные события в городе Дніпро / Днепр, заявления и решения ООН и НАТО, резонансные новости и законы о ТЦК/мобилизации, масштабные аварии/повреждения энергетики.\n"
            "- Для 'CS2': 1.0 - 4.0 сарказм, мемы, реклама рулеток/скинов. 7.0 - 9.5 официальные трансферы, победы в финалах (NaVi, Vitality, Spirit, s1mple).\n"
            "- Для 'IT': 8.0 - 10.0 ключевые релизы языков. 5.0 - 6.5 минорные патчи.\n\n"
            "Требования к языку и переводу:\n"
            "- Если заголовок или текст на украинском или английском языке — ОБЯЗАТЕЛЬНО переведи заголовок на русский язык и верни в поле russian_title.\n"
            "- short_summary: СТРОГО 2-3 кратких емких предложения с ключевой сутью на русском языке. Никакой воды.\n"
            "- why_it_matters: Кратко в 1 предложении почему это важно на русском языке.\n"
            "- key_points: 2-3 конкретных факта на русском языке.\n\n"
            "Формат JSON:\n"
            "{\n"
            '  "russian_title": "Заголовок на русском языке",\n'
            '  "short_summary": "Суть события (по-русски)",\n'
            '  "why_it_matters": "Значение новости для аудитории",\n'
            '  "key_points": ["Факт 1", "Факт 2"],\n'
            '  "importance_score": 7.5,\n'
            '  "category": "Украина"\n'
            "}"
        )

        truncated_text = text[:600]
        source_prefix = f"Источник: {source_name}\n" if source_name else ""
        user_prompt = f"{source_prefix}Заголовок: {title}\nТекст: {truncated_text}"

        payload: Dict[str, Any] = {
            "model": self.model,
            "system": system_prompt,
            "prompt": user_prompt,
            "stream": False,
            "format": "json",
            "options": {
                "temperature": 0.2,
                "num_ctx": 2048,
                "num_predict": 600,
            },
        }

        url = f"{self.base_url}/api/generate"

        try:
            logger.info("Sending article '%s' to Ollama (%s)...", title[:35], self.model)
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.post(url, json=payload)
                response.raise_for_status()

            data = response.json()
            raw_text = data.get("response", "").strip()

            parsed = json.loads(raw_text)
            result = ArticleAnalysisResult(**parsed)
            logger.info("Successfully analyzed '%s' (Score: %.1f, Cat: %s)", title[:30], result.importance_score, result.category)
            return result

        except httpx.TimeoutException:
            logger.error("Timeout waiting for Ollama for: %s", title[:35])
        except Exception as e:
            logger.error("Error during analysis: %s", e)

        return None
