import json
import logging
import re
from typing import Any, Dict, List, Optional
import httpx
from pydantic import BaseModel, Field, model_validator

from app.config import get_settings

logger = logging.getLogger("news_ai.ai.client")
settings = get_settings()


class ArticleAnalysisResult(BaseModel):
    """Structured analytical output generated by the local LLM."""

    russian_title: Optional[str] = Field(None, description="Заголовок новости на русском языке")
    short_summary: str = Field(default="Краткое резюме события.", description="1-2 sentences summary in Russian")
    why_it_matters: str = Field(default="Событие важно для контекста происходящего.", description="Why it matters in Russian")
    key_points: List[str] = Field(default_factory=list, description="2-3 key points in Russian")
    importance_score: float = Field(default=6.0, ge=1.0, le=10.0, description="Importance score")
    category: str = Field("IT", description="Topic category")

    @model_validator(mode="before")
    @classmethod
    def normalize_and_sanitize(cls, data: Any) -> Any:
        if isinstance(data, dict):
            # 1. Normalize score (handle missing or aliases like 'score', 'importance', 'rating')
            score = data.get("importance_score")
            if score is None:
                score = data.get("score") or data.get("importance") or data.get("rating")
            if score is not None:
                try:
                    data["importance_score"] = max(1.0, min(10.0, float(score)))
                except (ValueError, TypeError):
                    data["importance_score"] = 6.0
            else:
                data["importance_score"] = 6.0

            # 2. Normalize summaries and titles
            if not data.get("short_summary"):
                data["short_summary"] = data.get("summary") or data.get("description") or "Краткое резюме события."
            if not data.get("why_it_matters"):
                data["why_it_matters"] = data.get("importance_reason") or "Событие важно для контекста происходящего."
            if not data.get("russian_title"):
                data["russian_title"] = data.get("title")

            # 3. Strip any stray CJK ideographs if model generated them
            cjk_pattern = re.compile(r'[\u4e00-\u9fff]+')
            for field in ["russian_title", "short_summary", "why_it_matters"]:
                val = data.get(field)
                if isinstance(val, str) and cjk_pattern.search(val):
                    data[field] = cjk_pattern.sub("", val).strip()

        return data


class OllamaClient:
    """Asynchronous client optimized for AI analysis with local LLM."""

    def __init__(
        self,
        base_url: Optional[str] = None,
        model: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> None:
        self.base_url = (base_url or settings.OLLAMA_BASE_URL).rstrip("/")
        self.model = model or settings.OLLAMA_MODEL
        self.timeout = timeout or 180.0

    async def analyze_article(
        self,
        title: str,
        text: str,
        source_name: Optional[str] = None,
    ) -> Optional[ArticleAnalysisResult]:
        """Analyze article and return structured JSON."""
        system_prompt = (
            "Ты — AI-аналитик новостей. Проанализируй заголовок и текст статьи и верни СТРОГО валидный JSON без markdown:\n\n"
            "Категории (выбери одну): 'IT', 'AI & Нейросети', 'Linux & Инфраструктура', 'CS2', 'Украина', 'Swiss'.\n"
            "- 'Украина': все новости о ситуации в Украине, атаках, обстрелах, ПВО, городах (Дніпро/Днепр, Киев, Одесса, Харьков), международной политике (ООН, НАТО), ТЦК, мобилизации и энергетике. Все новости NovynaUKR — это 'Украина'!\n"
            "- 'CS2': киберспорт, турниры, команды (NaVi, Vitality, Spirit, FaZe), игроки (s1mple, m0NESY, ZywOo, donk), CS2, CS:GO, Clash Royale.\n"
            "- 'IT': программирование, языки (Python, Rust, Go, C++, JS/TS, Java, C#), разработка ПО.\n- 'Swiss': новости Швейцарии (источники Instagram: RTS, Blick, 20 minutes и др.). ВАЖНО: для категории 'Swiss' НЕ переводи текст на русский, верни заголовок и short_summary на оригинальном французском языке (en français)!\n\n"
            "Оценка важности (importance_score от 1.0 до 10.0):\n"
            "- 3.0 - 5.0: оперативные микро-сигналы о пролете единичных дронов/шахедов ('курсом на...', 'угроза по баллистике', 'летит дрон').\n"
            "- 7.5 - 9.5: важные события, сводки Воздушных сил, заявления ООН/НАТО, события в г. Дніпро/Днепр, новости о ТЦК и мобилизации, энергетика/удары.\n\n"
            "Язык и перевод:\n"
            "- СТРОГО русский язык. Категорически запрещены китайские иероглифы, украинские или английские слова в ответе!\n"
            "- Если заголовок или текст на украинском или английском языке — ОБЯЗАТЕЛЬНО переведи заголовок на русский язык и верни в поле russian_title.\n"
            "- short_summary: 1-2 кратких емких предложения сути на русском языке.\n"
            "- why_it_matters: 1 предложение почему это важно на русском языке.\n\n"
            "Формат JSON:\n"
            "{\n"
            '  "russian_title": "Заголовок на русском языке",\n'
            '  "short_summary": "1-2 предложения сути на русском",\n'
            '  "why_it_matters": "Почему это важно",\n'
            '  "key_points": ["Факт 1", "Факт 2"],\n'
            '  "importance_score": 8.5,\n'
            '  "category": "Украина"\n'
            "}"
        )

        truncated_text = text[:700]
        source_prefix = f"Источник: {source_name}\n" if source_name else ""
        user_prompt = f"{source_prefix}Заголовок: {title}\nТекст: {truncated_text}"

        payload: Dict[str, Any] = {
            "model": self.model,
            "system": system_prompt,
            "prompt": user_prompt,
            "stream": False,
            "format": "json",
            "options": {
                "temperature": 0.1,
                "num_ctx": 2048,
                "num_predict": 800,
            },
        }

        url = f"{self.base_url}/api/generate"

        try:
            logger.info("Sending article '%s' to Ollama (%s)...", title[:35], self.model)
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.post(url, json=payload)
                response.raise_for_status()

            data = response.json()
            raw_text = data.get("response", "").strip()

            try:
                parsed = json.loads(raw_text)
            except json.JSONDecodeError:
                start = raw_text.find("{")
                end = raw_text.rfind("}")
                if start != -1 and end != -1 and end > start:
                    parsed = json.loads(raw_text[start:end+1])
                else:
                    raise

            result = ArticleAnalysisResult(**parsed)
            logger.info("Successfully analyzed '%s' (Score: %.1f, Cat: %s)", title[:30], result.importance_score, result.category)
            return result

        except httpx.TimeoutException:
            logger.error("Timeout waiting for Ollama for: %s", title[:35])
        except Exception as e:
            logger.error("Error during analysis: %s", e)

        return None
